### ISSUE TITLE
Boutton "Rechercher" ne marche pas dans la partie "Recruteurs bloqués"

### ISSUE THREAD

**Issue by Laila-BENGHABRIT** [khalid-elabbadi/upforjob#15]
![image](https://user-images.githubusercontent.com/42932849/71169121-827e4080-2258-11ea-9283-7386f7c838ce.png)

**pour que ça marche, il faut que la personne clique sur le bouton rouge en haut (processus lent)**

**Comment by khalid-elabbadi** [comment]
Fixed

**Comment by Laila-BENGHABRIT** [comment]
Still doesn't work!

**Comment by khalid-elabbadi** [comment]
i think you do not understand how this screen works:
when you get in there, you will get the list of recruiters you already have blocked and because you blocked no one that list would be empty and searching in empty is empty

to block recruiters click on the top bouton block some people and retry again

**Comment by khalid-elabbadi** [comment]
![image](https://user-images.githubusercontent.com/31181469/71408786-aa4a1b80-263f-11ea-9fe5-9137b9e8c3eb.png)

**Comment by khalid-elabbadi** [comment]
![image](https://user-images.githubusercontent.com/31181469/71408826-c9e14400-263f-11ea-91e2-2d4ffd0d5598.png)

**Comment by Laila-BENGHABRIT** [comment]
GOT  IT !
